version: "2"

services:
    web_server:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./post_service:/post_service
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - backend-network 
    php:
        build: ./post_service
        env_file:
            - ./post_service/.env
        volumes:
            - ./post_service:/post_service
        networks:
            - backend-network
    redis:
        image: redis:latest
        ports: ["6379"]
        networks:
            - backend-network
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - "db-data:/var/lib/postgresql/data"
        networks:
            - backend-network
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "9000:80"
        environment: 
            - PGADMIN_DEFAULT_EMAIL=abinmt
            - PGADMIN_DEFAULT_PASSWORD=password
        networks:
            - backend-network

volumes:
    db-data:

networks:
    backend-network:
        driver: bridge
